backend:
  name: test-repo

# These lines should match your local URL
site_url: http://localhost:4321
display_url: http://localhost:4321

# Copy the rest of the collections config from the main config.yml
collections:
  - name: 'blog'
    label: 'Articles'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Image principale',
          name: 'image',
          widget: 'image',
          required: false,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/pages/about.mdx'
        label: 'À propos'
        name: 'about'
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
