backend:
  name: git-gateway
  repo: PierreTsia/margot-relooking
  branch: main

# Enable Netlify Identity integration
identity_url: 'https://margot-relooking.netlify.app/.netlify/identity'
gateway_url: 'https://margot-relooking.netlify.app/.netlify/git/github'

# These lines should match your deployment URL
site_url: https://margot-relooking.netlify.app
display_url: https://margot-relooking.netlify.app

# Media handling
media_folder: 'public/images/blog'
public_folder: '/images/blog'
media_library:
  name: 'uploadcare'
  max_file_size: 2000000 # 2MB
  allowed_extensions: ['png', 'jpg', 'jpeg', 'webp']
  choose_url: false
  config:
    multiple: false
    publicKey: 'demo'

# Content Collections
collections:
  - name: 'blog'
    label: 'Articles'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Image principale',
          name: 'image',
          widget: 'image',
          required: false,
          hint: 'Format recommandé: 1200x675px (16:9). Max 2MB.',
          choose_url: false,
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/pages/about.md'
        label: 'À propos'
        name: 'about'
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
