backend:
  name: git-gateway
  repo: PierreTsia/margot-relooking
  branch: main

# Enable Netlify Identity integration
identity_url: 'https://margot-relooking.netlify.app/.netlify/identity'
gateway_url: 'https://margot-relooking.netlify.app/.netlify/git/github'

# These lines should match your deployment URL
site_url: https://margot-relooking.netlify.app
display_url: https://margot-relooking.netlify.app

# Media handling
media_folder: 'public/images/blog'
public_folder: '/images/blog'

# Content Collections
collections:
  - name: 'blog'
    label: 'Articles'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - {
          label: 'Description',
          name: 'description',
          widget: 'text',
          required: false,
        }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Brouillon', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Auteur',
          name: 'author',
          widget: 'string',
          required: false,
          default: 'Margot'
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          required: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
          hint: 'Ajoutez des tags pour catégoriser votre article'
        }
      - {
          label: 'Image principale',
          name: 'image',
          widget: 'image',
          required: false,
          hint: 'Format recommandé: 1200x675px (16:9). Max 2MB.',
          choose_url: false,
        }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/content/pages/about.md'
        label: 'À propos'
        name: 'about'
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Photo de profil', name: 'image', widget: 'image' }
          - { label: 'Introduction', name: 'intro', widget: 'text' }
          - label: 'Mission'
            name: 'mission'
            widget: 'object'
            fields:
              - { label: 'Titre', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Objectifs'
            name: 'objectives'
            widget: 'list'
            field: { label: 'Objectif', name: 'objective', widget: 'string' }
          - label: 'Valeurs'
            name: 'values'
            widget: 'list'
            fields:
              - { label: 'Titre', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Approche'
            name: 'approach'
            widget: 'object'
            fields:
              - { label: 'Titre', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - label: 'Étapes'
                name: 'steps'
                widget: 'list'
                fields:
                  - { label: 'Numéro', name: 'step', widget: 'string' }
                  - { label: 'Titre', name: 'title', widget: 'string' }
                  - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Call to Action'
            name: 'cta'
            widget: 'object'
            fields:
              - { label: 'Titre', name: 'title', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
